# -*- coding: utf-8 -*-
"""run_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ffer5rXTQaJ2RnVs5WMKeC6gms9qXIFJ
"""

"""
run_pipeline.py

Pipeline script to run the full MeSH Analysis in the correct order.
      1. mesh_data_processor.py
      2. master_mesh_network.py
      3. secondary_analysis.py
      4. figures.py
  See README.txt for full descriptions of scripts

Ensure that config.py is set up prior to running.
[!] NOTE: Biological strata assignment must be assigned manually after secondary_analysis.py step.
      Use the results/FILE_PREFIX_Mesh_final_network_with_relevance_export.xlsx and update data/raw/aop_annotations_master.csv
      Figures will be generated regardless with this pipline but may not be accurate if assignment is not performed.
"""

import os
import subprocess
import sys
import time

def run_script(script_path, description):
    """
    Runs a python script using subprocess and checks for errors.
    """
    if not os.path.exists(script_path):
        # Optional: Skip if it's the figures script and doesn't exist yet
        if "figures.py" in script_path:
            print(f"\n[!] Notice: '{script_path}' not found. Skipping figure generation.")
            return True
        else:
            print(f"\n[ERROR] Script not found: {script_path}")
            return False

    print(f"\n" + "<"*30 + ">"*30)
    print(f">>> STARTING: {description}")
    print(f">>> Script:   {script_path}")
    print("<"*30 + ">"*30 + "\n")

    start_time = time.time()
    try:
        subprocess.run([sys.executable, script_path], check=True)

        elapsed = time.time() - start_time
        print(f"\n>>> SUCCESS: {description} completed in {elapsed:.2f} seconds.")
        return True

    except subprocess.CalledProcessError as e:
        print(f"\n[ERROR] Pipeline failed at step: {description}")
        print(f"Exit code: {e.returncode}")
        return False
    except Exception as e:
        print(f"\n[ERROR] Unexpected error running {description}: {e}")
        return False

if __name__ == "__main__":
    SCRIPTS_DIR = os.path.join("scripts", "python")

    # Define steps
    pipeline_steps = [
        (
            os.path.join(SCRIPTS_DIR, "mesh_data_processor.py"),
            "Step 1: Data Processing & Stop Word Generation"
        ),
        (
            os.path.join(SCRIPTS_DIR, "master_mesh_network.py"),
            "Step 2: Master Network Construction & Analysis"
        ),
        (
            os.path.join(SCRIPTS_DIR, "secondary_analysis.py"),
            "Step 3: Secondary Analysis & Excel Export"
        ),
        (
            os.path.join(SCRIPTS_DIR, "figures.py"),
            "Step 4: Figure Generation"
        )
    ]

    print("<"*30 + ">"*30)
    print("STARTING MESH NETWORK ANALYSIS PIPELINE")
    print("<"*30 + ">"*30)

    # <<< CONFIG CHECK & WARNING SYSTEM >>>
    # Dynamically import config to check flags
    try:
        sys.path.append(os.path.join(os.getcwd(), 'scripts', 'python'))
        import config

        if hasattr(config, 'USE_REFERENCE_DATA') and not config.USE_REFERENCE_DATA:
            print(f"\n" + "<"*30 + ">"*30)
            print("[!] WARNING: REFERENCE DATA IS DISABLED")
            print("    Manual biological strata assignment is required for accurate figure generation.")
            print("    Please update 'data/raw/aop_annotations_master.csv' after Step 3.")
            print("    Assign one of the following 7 levels to new terms:")
            print("    Stressor, Molecular, Cellular, Tissue, Organ, Adverse Outcome, or Uncategorized")
            print("<"*30 + ">"*30 + "\n")

            # Optional: Pause to let the user read the warning
            time.sleep(2)

    except ImportError:
        print("\n[!] Notice: Could not import 'config.py' to verify reference settings.\n")

    # <<< PIPELINE EXECUTION >>>
    total_start = time.time()
    success = True

    for script_path, description in pipeline_steps:
        if not run_script(script_path, description):
            success = False
            break

    print("\n" + "<"*30 + ">"*30)
    if success:
        total_time = time.time() - total_start
        print(f"PIPELINE COMPLETED SUCCESSFULLY in {total_time/60:.2f} minutes.")
    else:
        print("PIPELINE TERMINATED WITH ERRORS.")
    print("<"*30 + ">"*30)

    if not success:
        sys.exit(1)

!pip install openpyxl