# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N41BpPuN8PwRTjG6a3l_UDqfIBDQwgv-
"""

"""
MeSH AOP Network Analysis Package

Initializes the package and exposes the primary pipeline functions,
creating a clean and modular API for network generation, statistical
filtering, and visualization.
"""

__version__ = "2.0.0"

# --- 1. Configuration ---
from .config_parser import MeshConfig

# --- 2. Data Processing (MARC/ASCII) ---
from .mesh_data_processor import process_raw_mesh_data

# --- 3. Database Operations & Entrez Fetching ---
from .data_ops import (
    run_initial_data_collection,
    clean_database,
    populate_master_mesh_database,
    update_db_with_mesh_batch
)

# --- 4. Network Construction ---
from .network import (
    run_network_construction,
    run_consensus_filtering_and_lcc,
    run_community_detection
)

# --- 5. Filtering & Relevance Scoring ---
from .relevance import (
    run_contextual_relevance_scoring
)

# --- 6. Secondary Analysis & Export ---
from .secondary_analysis import (
    analyze_node_relevancy,
    analyze_edge_relevancy,
    get_top_network_articles,
    convert_network_json_to_excel
)

# --- 7. Visualization ---
from .viz import (
    analyze_dispersion,
    plot_cooccurrance_distribution,
    run_optimization_comparison,
    plot_louvain_community_bars,
    plot_joint_plot,
    plot_tsne_louvain_overlap,
    plot_sankey_alluvial,
    plot_dumbell_plot,
    plot_scatter_panels,
    plot_dendrogram,
    generate_filtering_summary_sankeys
)

# Define the public API of the package
__all__ = [
    "MeshConfig",
    "process_raw_mesh_data",
    "run_initial_data_collection",
    "clean_database",
    "populate_master_mesh_database",
    "update_db_with_mesh_batch",
    "run_network_construction",
    "run_community_detection",
    "run_consensus_filtering_and_lcc",
    "run_contextual_relevance_scoring",
    "analyze_node_relevancy",
    "analyze_edge_relevancy",
    "get_top_network_articles",
    "convert_network_json_to_excel",
    "analyze_dispersion",
    "plot_cooccurrance_distribution",
    "run_optimization_comparison",
    "plot_louvain_community_bars",
    "plot_joint_plot",
    "plot_tsne_louvain_overlap",
    "plot_sankey_alluvial",
    "plot_dumbell_plot",
    "plot_scatter_panels",
    "plot_dendrogram",
    "generate_filtering_summary_sankeys"
]